name = "bonsai"
main = "src/index.ts"
compatibility_date = "2022-06-22"
node_compat = true

[vars]
# The necessary secrets are:
# - APPLICATION_ID
# - APPLICATION_SECRET
# - PUBLIC_KEY
# - DB_URL
# - DB_KEY

[env.dev]
name = "bonsai-dev"
[env.dev.vars]
# The necessary secrets are:
# - APPLICATION_ID
# - APPLICATION_SECRET
# - PUBLIC_KEY
# - DB_URL
# - DB_KEY
